### ISSUE TITLE
How to increase rpc timeout value

### ISSUE THREAD

**Issue by Barathi07** [OpenClovis/OpenYuma#23]
Hi,
 Am facing the following error, when i execute the rpc (which starts vswitchd process, which will take 40-50 seconds).
ERROR:
**mgr_rpc: deleting timed out request '4'
Error: request to server timed out
**
Can you please tell me , where to increase the timeout value in openyuma src files?

**Comment by hoangle** [comment]
I guest this timeout happened at yangcli since default timeout on <rpc> at remote is set to 3600seconds.
To increase the timeout at remote, let's use --idle-timeout param and --timeout for yangcli.
Refer to document:openyuma-netconfd-manual.odt and openyuma-yangcli-manual.odt located in OpenYuma/netconf/doc/yuma_docs/ to know how to configure these params

**Comment by Barathi07** [comment]
Thanks Hoangle..It worked..
